name = "bglrr"
main = ".open-next/worker.js" 
compatibility_date = "2026-08-01"
compatibility_flags = [ "nodejs_compat" ] 

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
LIVEKIT_URL = "wss://bglrr-47geizud.livekit.cloud"
NEXT_PUBLIC_LIVEKIT_URL = "wss://bglrr-47geizud.livekit.cloud"
NEXT_PUBLIC_SUPABASE_URL = "https://eijkkwpxlazgigqfjelf.supabase.co"

[secrets]
required = [
  "LIVEKIT_API_KEY",
  "LIVEKIT_API_SECRET",
  "DEEPGRAM_API_KEY",
  "SUPABASE_SECRET_KEY",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" 
]
